using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HomeSeek.Entities
{
    public enum CountiesOfGreece
    {
        Achaea,
        Aetolia,
        Arcadia,
        Argolis,
        Arta,
        Athens,
        Attica,
        Boeotia,
        Cephalonia,
        Chalkidiki,
        Chania,
        Chios,
        Corfu,
        Corinthia,
        Cyclades,
        Dodecanese,
        Drama,
        Evia,
        Evros,
        Evrytania,
        Florina,
        Fokida,
        Fthiotida,
        Grevena,
        Heraklion,
        Ikaria,
        Ilia,
        Imathia,
        Ioannina,
        Islands,
        Ithaca,
        Karditsa,
        Kastoria,
        Kavala,
        Kilkis,
        Kozani,
        Laconia,
        Larissa,
        Lasithi,
        Lefkada,
        Lemnos,
        Lesbos,
        Magnesia,
        Messinia,
        Pella,
        Pieria,
        Piraeus,
        Preveza,
        Rethymno,
        Rhodope,
        Samos,
        Serres,
        Sporades,
        Thesprotia,
        Thessaloniki,
        Trikala,
        Xanthi,
        Zakynthos
    }
}
